#!/bin/sh
webtorrent $(curl -s "https://www.1377x.to$(curl -s "https://www.1377x.to/sort-category-search/$(echo "Play movie: " | dmenu | tr ' ' '+')/Movies/seeders/desc/1/" | grep -P '/torrent/[0-9]*/' | head -n 1 | cut -d '"' -f 4)" | grep -P 'magnet:.+' | head -n 1 | cut -d '"' -f 4) -q --mpv &
